url=jdbc:mysql://localhost:3306/libreriadb_in4cm?serverTimezone=UTC
user=in4cm
password=09012011

db.url=jdbc:mysql://localhost:3306/libreriadb_in4cm?serverTimezone=UTC
db.user=in4cm
db.password=09012011


